aircond_rails_app/config/routes.rb
require 'sidekiq/web'
require 'sidekiq/cron/web'
Rails.application.routes.draw do

mount Sidekiq::Web => '/sidekiq'
  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "sessions", only: [:create]

  resources :users, controller: "users", only: [:create] do
    resource :password,
      controller: "clearance/passwords",
      only: [:create, :edit, :update]
  end

  get "/sign_in" => "sessions#new", as: "sign_in"
  delete "/sign_out" => "sessions#destroy", as: "sign_out"
  constraints Clearance::Constraints::SignedIn.new do
    root to: 'aircond_groups#index', as: :admin_root
  end

  constraints Clearance::Constraints::SignedOut.new do
    root to: 'sessions#new'
  end


  get '/react_test' => 'users#react_test'


  post '/firebase_update/:id' => 'airconds#update_website_from_firebase', as: :firebase_update
  resources :aircond_groups, only: [:create,:destroy,:index,:show]

  resources :devices
  resources :airconds do
    resources :versions, only: [:index]
  end
  get 'aircond/:id/timer' => 'airconds#timer', as: :set_timer
  patch 'aircond/:id/timer' => 'airconds#timer_set', as: :timer_set
  post 'set_all_status/:status' => 'airconds#set_all_status', as: :set_all_status
  post 'limit_options' => 'airconds#limit_options', as: :limit_options
  patch 'aircond/:id/assign_group' => 'airconds#assign_group', as: :assign_group

  post '/app_state/:id' => 'airconds#app_set', as: :app_set

  get '/auth/nextacademy/callback' => 'sessions#create_from_omniauth'

  resources :phone_apps, only: [:index]
  post '/app_create' => 'phone_apps#create', as: :app_create
  patch '/approve_token/:id' => 'phone_apps#approve_token', as: :approve_token
  get '/get_token' => 'phone_apps#provide_token', as: :get_token
  get '/validate_token' => 'phone_apps#check_token', as: :validate_token
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

aircond_rails_app/app/models/aircond.rb
require 'unirest'

class Aircond < ApplicationRecord
	belongs_to :device
  belongs_to :aircond_group,  optional: true
	belongs_to :aircond_state,  optional: true
  has_paper_trail
  before_update :check_state
  after_save :update_firebase
  scope :by_aircond_group,  -> (ac_grp_id){where('aircond_group_id =  ?', ac_grp_id)}
  scope :by_unassigned_aircond_group,  -> {where('aircond_group_id IS NULL')}

  attr_accessor :from_firebase
	  enum status:{
	    'OFF' =>0,
	    'ON' =>1,
	    'PENDING' =>2
	  }

	  enum mode:{
	    'DRY' =>0,
	    'WET' =>1,
	    'COLD' => 2
	  }

	  enum fan_speed:{
	    'AUTO' =>0,
	    '1' =>1,
	    '2' =>2,
	    '3' =>3
	  }

	def get_state
		raspi = self.device
		path = raspi.url + "/state.py"
    response = Unirest.get(path,parameters:{access_token:raspi.access_token})
    #assumes that receive a hash {status:"ON"}
		return {status:true}
	end

	def send_signal(command)
		raspi = self.device
		path = raspi.url + "/state.py"
    params = {access_token: raspi.access_token, command:command}
		response = Unirest.post(path,parameters:params)

		check_power_status(self.changes['status'][1]) if self.changes.keys.include?(:status) && !self.changes[key].nil?
	end

	def update_firebase
    if from_firebase == false
  		firebase = Firebase::Client.new("https://nextaircon-6d849.firebaseio.com")
  		data = self.slice(:alias,:temperature,:mode,:fan_speed,:aircond_group_id)
      data[:pi_status] = "ENABLED"
  		firebase.update('/airconds/'+self.id.to_s, data)
    end
	end

   def check_state
     if from_firebase == false
       response = send_signal(get_command) if !(self.changes.keys & ["status","temperature","mode","fan_speed"]).empty?
       throw :abort if response == false
     end
   end

	def check_power_status(arg)
		get_state[:status] == arg
	end

	def check_device_status
     begin
       Unirest.get(self.device.url)
     rescue Errno::EHOSTUNREACH
       false
     else
			true
     end
	end

	def get_command
		data = self.slice(:status,:temperature, :mode, :fan_speed)
		data.keys.each do |key|
			data[key] = self.changes[key][1] if self.changes.keys.include? key
		end
		data = data.slice(:temperature,:mode, :fan_speed) if !self.changes.keys.include? 'status' || check_power_status(self.changes['status'][1])
		decipher_command(data)
	end

  def set_id
     response = Unirest.post(self.device.url + '/set_id.py',parameters:{id:self.id})
  end

  def formatted_timer(status,t_format=nil)
    case status
    when "ON"
      output = Time.zone.parse(self.timer_on.to_s)
    when "OFF"
      output = Time.zone.parse(self.timer_off.to_s)
    end
    output = output.strftime('%H:%M') if t_format == 'strf' && !output.nil?
    return output
  end

  def image_new(attribute)
  	value = self.send(attribute)
  	value = 'NA' if value == nil
  	case attribute
  		when :status
  			{img_url:"/NEXT-AC-assets/power-#{value.downcase}-01.png",value:value}
  		when :mode
				{img_url:"/NEXT-AC-assets/mode-#{value.downcase}-on.png",value:value}
  		when :fan_speed
  			{img_url:"/NEXT-AC-assets/speed-#{value.to_s.downcase}-on.png",value:value}
  		when :temperature
				{img_url:"/NEXT-AC-assets/temp-#{value.to_s}.png",value:value}
			end
  end
end

aircond_rails_app/app/controllers/airconds_controller.rb
class AircondsController < ApplicationController
	before_action :set_aircond, only: [:edit,:update,:timer,:timer_set,:app_set,:update_website_from_firebase,:assign_group]
	before_action only: [:app_set] {validate_app_token(params[:user_name],params[:app_token])}
	skip_before_filter  :verify_authenticity_token, only: [:app_get_all,:app_set]
	before_action :set_paper_trail_whodunnit, only: [:create,:update,:set_all_status]
	def new
		@aircond = Aircond.new
		@current_time= Time.zone.now
	end

	def create
		device= Device.new(device_params)
		if device.save
			ac = Aircond.new(device_id:device.id,alias:aircond_params[:alias])
			ac.save
			ac.set_id
			ac.update(status:'OFF',mode:'COLD',fan_speed:'AUTO',temperature:20)
			redirect_to root_path
		else
			@aircond = Aircond.new
			flash[:warning] = "#{device.errors.full_messages[0]}"
			render :new
		end
	end

	def edit
		generate_selection(@aircond.mode)
		@current_time= Time.zone.now
		respond_to do |format|
			format.html {}
			format.js {
				generate_selection(params[:mode])
				render json:{fan_speed:@fan_speed_selection,temperature:@temperature_selection}
			}
		end
	end

	def update
			@current_time= Time.zone.now
			@aircond.update(alias:aircond_params[:alias]) if aircond_params.keys.include? "alias"
			cmd = decipher_command(aircond_params)
			generate_selection(@aircond.mode)
			@path = :edit

			if validate_AC_controls(cmd)
				if @aircond.check_device_status
					if @aircond.update(aircond_params)
            render json: { aircond: @aircond }
            return
					else
						@error = "Aircond state was not change. Remains as #{@aircond.get_state[:status]}"
					end
				else
					@error = 'Raspberry Pi might not be on.'
				end
			else
				@error = "Invalid command signal"
			end

      render status: :bad_request, json: { error: @error }
	end

	def assign_group
		@aircond.aircond_group_id = params[:aircond][:aircond_group_id]
		@aircond.save
	end



	def timer_set
		#sets the job for timer to execute
		timer_type = "timer_#{params[:aircond][:status].downcase}"
		trigger_time = Time.zone.parse(params.permit![:aircond][timer_type.to_sym])
		job = Sidekiq::Cron::Job.new(name:"AcTimer worker - #{@aircond.alias} - #{timer_type}", cron: " #{trigger_time.min} #{trigger_time.hour} * * 1-5 #{Time.zone.name}", class:'AcTimerWorker', args:{aircond_id:@aircond.id,status:params[:aircond][:status]})
		if job.save
			@aircond.update(timer_type.to_sym =>Time.zone.local_to_utc(trigger_time))
			redirect_to root_path
		else
			flash[:warning] = 'Invalid Job'
			redirect_to set_timer_path
		end
	end

	def set_all_status
		#sets all the aircond statuses..
		ac_grp = AircondGroup.find_by_title(params[:aircond][:group_title])
		ac_grp.nil? ? @airconds = Aircond.all : @airconds = ac_grp.airconds

		@airconds.each do |ac|
			ac.from_firebase = false
			# ac.send_signal(params[:status]) if ac.get_state[:status] != params[:status]
			# ac.update(status:ac.get_state[:status])
			ac.update(status:params[:status])
		end

		flash[:warning] = "Airconds with aliases  #{Aircond.where('status != ?', Aircond.statuses[params[:status]]).pluck(:alias)} were not successfully #{params[:status]}"
		redirect_to root_path
	end

	def limit_options
		#ajax path to responsively limit the options on edit page on selection of aircond mode
		generate_selection(params[:mode])
		render json:{fan_speed:@fan_speed_selection, temperature:@temperature_selection}
	end

	def app_set
		PaperTrail.whodunnit = params[:user_name]
		if validate_app_token(params[:user_name],params[:app_token])
			cmd = decipher_command(aircond_params)
			if validate_AC_controls(cmd)
				if @aircond.check_device_status
					if @aircond.check_power_status(aircond_params['status'])
						@aircond.update(aircond_params)
						msg = "Aircond is already #{aircond_params[:status]}. Mode: #{aircond_params[:mode]},Temperature: #{aircond_params[:temperature]}, Fan Speed : #{aircond_params[:fan_speed]}"
					elsif @aircond.update(aircond_params)
						msg = "Aircond state was successfuly changed. Mode: #{aircond_params[:mode]},Temperature: #{aircond_params[:temperature]}, Fan Speed : #{aircond_params[:fan_speed]}"
					else
						msg = "Aircond state was not change. Remains as #{@aircond.get_state[:status]}"
					end
				else
					msg = 'Raspberry Pi might not be on.'
				end
			else
				msg = "Invalid command signal"
			end
		else
			msg = "Invalid Token"
		end
		render json:{response:msg}
	end

	# def update_website_from_firebase
	# 	PaperTrail.whodunnit = 'firebase'
	# 	arguments = aircond_params
	# 	sanitize_params(arguments)
	# 	@aircond.from_firebase = true
	# 	@aircond.update(arguments)

	# 	render json:{response:'Updated'}
	# end

	private

	def device_params
		params.require(:aircond).require(:device).permit(:url)
	end

	def aircond_params
		params.require(:aircond).permit(:status,:mode,:fan_speed,:temperature,:alias)
	end

	def set_aircond
		@aircond = Aircond.find(params[:id])
		@aircond.from_firebase = false
	end

	def sanitize_params(arguments)
		arguments[:temperature] = arguments[:temperature].to_i if !arguments[:temperature].nil?
		arguments[:fan_speed] = Aircond.fan_speeds[arguments[:fan_speed]]
	end

	def generate_selection(mode)
		#generate the options available for views
		@fan_speed_selection = Aircond.fan_speeds.keys
		@temperature_selection = (16..30).to_a
		if mode == 'DRY'
			@fan_speed_selection = @fan_speed_selection - ["AUTO"]
			@temperature_selection = []
		elsif mode == 'WET'
			@fan_speed_selection = []
		elsif mode == nil
			@fan_speed_selection = []
			@temperature_selection = []
		end
	end

	def validate_AC_controls(commands)
		#ENSURE no invalid commands sent
		previous_cmd = true
		cmd_validity = true
		commands.split(' ').each do |command|
			current_cmd = InfraredSignal.pluck(:command).include? command
			cmd_validity = previous_cmd && current_cmd
			previous_cmd = cmd_validity
		end
		return cmd_validity
	end

	def validate_app_token(user_name,token)
		app_token = PhoneApp.find_by(user_name:user_name)
		token == app_token.access_token if !app_token.nil?
	end
end

aircond_rails_app/app/helpers/airconds_helper.rb
module AircondsHelper
end

aircond_rails_app/app/views/airconds/_aircond.html.erb
      <div id = <%= "#{aircond.id}"%> class = 'aircond ac_row col-sm-12'   style= 'background-color: #E8E8EE;height:auto;width:auto;min-height: 100px; margin-bottom: 5px'>
        <div class = 'col-sm-8' style = 'padding:0px'>
          <div class = 'col-sm-12' style = 'height:50px;font-size:30px;text-align: center;vertical-align: middle;font-style:italic;'><%= aircond.alias%> 
          </div>
          <div class = "ac_mode col-sm-5" style = 'height:50px'>
          <% mode = aircond.image_new(:mode)%> 
              <%= image_tag(mode[:img_url],class:'fit-img-size ', align:'middle' )%>
          </div>
          <div  class = "ac_fan_speed col-sm-3" style = 'height:50px;text-align: center;font-size:30px'>
          <% fan_speed = aircond.image_new(:fan_speed)%> 
            <% if fan_speed[:value] == 'NA'%>
              <%= fan_speed[:value]%> 
            <% else %>
              <%= image_tag(fan_speed[:img_url],class:'fit-img-size ', align:'middle' )%>
            <%end%>
          </div>
          <div class = "ac_temperature col-sm-4" style = 'height:50px;text-align: center;font-size:30px'>
          <% temperature = aircond.image_new(:temperature)%>
            <% if temperature[:value] == 'NA'%>
              <%= temperature[:value]%> 
            <% else %>
              <%= image_tag(temperature[:img_url],class:'fit-img-size ', align:'middle' )%>
            <% end %>
          </div>
        </div>
        <div class = ' ac_status col-sm-4' id = <%="#{aircond.alias}"%> style = 'height:100px;'>
          <% status = aircond.image_new(:status)%>
              <%= image_tag(status[:img_url],class:'fit-img-size ' , align:'middle')%>
        </div>

      </div>

aircond_rails_app/app/views/airconds/_aircond_layout.html.erb
<div style = 'clear:both'></div>


<%= select_tag 'location', options_for_select(['AG7','AG8_top','AG8_btm','AG1_11'])%>

<div class = 'layout' id= 'AG7'>
AG7
</div>
<div class = 'layout' id= 'AG8_top'>
AG8 Top
  <div class = 'layout_tile' id= 'AG8_top_1' style= ' '>
    AG8-1
  </div>
  <div class = 'layout_tile' id= 'AG8_top_2' style= ''>
    AG8-2
  </div>
</div>
<div class = 'layout' id= 'AG8_btm'>
AG8 Bottom

</div>
<div class = 'layout' id= 'AG1_11'>
AG1-11

</div>

aircond_rails_app/app/views/airconds/_aircond_timer_form.html.erb
  <div style = 'border-top-style:solid'>
    <h1><%= timer_input %>-Timer</h1>
        <%=form_for @aircond, url:timer_set_path(@aircond) do |f|%>
          <%=f.time_field "timer_#{timer_input.downcase}".to_sym, value: @aircond.formatted_timer(timer_input,'strf'),class:'form-control right_align',style:'width:120px;'%>
          <%=f.hidden_field :status, value: timer_input%>
          <%=f.submit "Set Timer",class:"btn btn-primary submit-btn"%>
      <%end%>

      <div style = 'float:right'><span >Current Timer  :</span>
        <% current_timer = @aircond.formatted_timer(timer_input) %>
        <% if !current_timer.nil?%>
          <div id=current_timer style = 'float:right'>
            <span id=hour><%= "#{current_timer.hour}".rjust(2,'0')%></span>:<span id=min><%="#{current_timer.min}".rjust(2,'0')%></span>:<span id=sec><%="#{current_timer.sec}".rjust(2,'0')%></span>
          </div>
        <%else%>
          <div> No Timer Set</div>
        <%end%>
        <div style = 'clear:right'></div>
        <div style = 'float:right'>Timezone: <%=Time.zone%></div>
      </div>  
      <div>
        <%= flash[:warning]%>
        <%= flash[:notice]%>
        <p  id = notification></p>
      </div> 
  </div>

aircond_rails_app/app/views/airconds/_form.html.erb
	<div id = ac_status>
		<%= form.label :status %>
		<%= form.select :status, Aircond.statuses.keys, {}, {class:'right_align form-control'}%>
	</div>

	<div id = ac_mode>	
		<%= form.label :mode %>
		<%= form.select :mode,Aircond.modes.keys, {}, {class:'right_align form-control'} %>
	</div>


	<div id = ac_fan_speed>
		<% if !@fan_speed_selection.empty?%>
			<%= form.label :fan_speed %>
			<%= form.select :fan_speed, @fan_speed_selection, {}, {class:'right_align form-control'} %>
		<%end%>
	</div>



	<div id = ac_temperature>
		<% if !@temperature_selection.empty?%>
			<%= form.label :temperature %>
			<%= form.select :temperature, @temperature_selection, {}, {class:'right_align form-control'}%>
		<% end%>
	</div>	

	<div>
  	<%= form.label :alias, 'Aircond Alias' %>
  	<%= form.text_field :alias, {class:'right_align form-control',style:'width:500px'}%>	
	</div>
	<%= form.submit 'Set Aircond State',class:"btn btn-primary submit-btn"%>

aircond_rails_app/app/views/airconds/edit.html.erb
<div class="col-sm-10" >
    <h1>Aircond Status</h1>
        <%= flash[:warning]%>
        <%= flash[:notice]%>
    <br>
    <%= form_for @aircond, html:{id:'edit_aircond_settings'} do |form|%>

      <div class = 'col-sm-8'>
        <div class = 'col-sm-12' style='height:100px'>
          <%= form.text_field :alias, {class:'form-control',style:'width:auto;height:auto;font-size:30px'}%>    
        </div>
        <div class = 'col-sm-12' id = ac_mode style='height:100px'>  
          <%= form.hidden_field :mode%>
        <div class = 'col-sm-2'><span>Mode</span></div>
        <% Aircond.modes.keys.each do |key|%>
          <% state = 'off'%>
          <% state = 'on' if key == @aircond.mode%>
            <div class = 'col-sm-2'><%= image_tag("/NEXT-AC-assets/mode-#{key.downcase}-#{state}.png",class:'fit-img-size ', align:'middle' )%></div>
        <% end %>
        </div>
        <div class = 'col-sm-12 ' id = ac_fan_speed style='height:100px'>
            <%= form.hidden_field :fan_speed %>
            <div class = 'col-sm-2'><span>Fan Speed</span></div>
            <% Aircond.fan_speeds.keys.each do |key| %>
              <div class = 'col-sm-2' id = <%="speed_#{key.to_s.downcase}"%>>
              <% if @fan_speed_selection.include?(key)%>
                <% state = 'off'%>
                <% state = 'on' if key == @aircond.fan_speed%>
                <%= image_tag("/NEXT-AC-assets/speed-#{key.to_s.downcase}-#{state}.png",class:'fit-img-size ', align:'middle' )%> 
              <% end %>
              </div>
            <% end %>
        </div>
      </div>

      <div class = 'col-sm-4' >
        <div class = 'col-sm-12' id = ac_status>
          <%= form.hidden_field :status%>
          <div >
            <% status = @aircond.image_new(:status)%>
              <%= image_tag(status[:img_url],class:'' ,style:'height:300px', align:'middle')%>
          </div>

        </div>

      </div>
      <div class = 'col-sm-12'>
      <div class = 'col-sm-12' id = ac_temperature style='height:100px'>

        <div class = 'col-sm-2'><span>Temperature</span></div>
        <div class = 'col-sm-8' id = 'temp_input'><%= form.range_field :temperature, in: 16..30%></div>
        <div class = 'col-sm-2' id = 'temp_img'>
          <% temperature = @aircond.image_new(:temperature)%>
            <% if temperature[:value] == 'NA'%>
            <% else %>
              <%= image_tag(temperature[:img_url],class:'fit-img-size ', align:'middle' )%>
            <% end %>
        </div>
      </div> 
      </div>
 

      <div class = 'col-sm-12'>
      <%= form.submit 'Set Aircond State',class:"btn btn-primary submit-btn"%>
      </div>  

    <%end%>

</div>

<div class="col-sm-2" style = 'border-left-style: solid;border-bottom-style: solid; padding: 20px;text-align : right'>
  <%= render partial:'/users/currenttime'%>
  <%= render partial:'aircond_timer_form.html.erb',locals:{timer_input:"ON"}%>
  <%= render partial:'aircond_timer_form.html.erb',locals:{timer_input:"OFF"}%>
</div>
<div class = 'col-sm-10'><span style = 'float:right'><%= link_to('Logs', aircond_versions_path(@aircond), method:'get',class:"btn btn-primary get-btn") if is_admin? %></span>
</div>

aircond_rails_app/app/views/airconds/new.html.erb
    <div class="col-sm-10"  >
  <%= form_for @aircond do |f|%>
  	<%= f.fields_for :device do |device_field|%>
  	
  		<%= device_field.label :url%>
  		<%= device_field.text_field :url,class:'form-control right_align',style:'width:300px' %>

  	<%end%>

    <br>
    <div style='clear:both'></div>
  	<%= f.label :alias, 'Aircond Alias' %>
  	<%= f.text_field :alias,class:'form-control right_align',style:'width:300px'%>
    <br>
  	<%= f.submit 'Create Aircond' ,class:"btn btn-primary submit-btn"%>
  <%end%>

  <div ><%=flash[:warning]%></div>

</div>

    <div class="col-sm-2" style = 'border-left-style: solid;border-bottom-style: solid; padding: 20px;text-align : right'>
      <%= render partial:'/users/currenttime'%>
    </div>

aircond_rails_app/app/views/airconds/signal.js.erb
PENDING_RESPONSE = false