aircond_rails_app/config/routes.rb
require 'sidekiq/web'
require 'sidekiq/cron/web'
Rails.application.routes.draw do

mount Sidekiq::Web => '/sidekiq'
  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "sessions", only: [:create]

  resources :users, controller: "users", only: [:create] do
    resource :password,
      controller: "clearance/passwords",
      only: [:create, :edit, :update]
  end

  get "/sign_in" => "sessions#new", as: "sign_in"
  delete "/sign_out" => "sessions#destroy", as: "sign_out"
  constraints Clearance::Constraints::SignedIn.new do
    root to: 'aircond_groups#index', as: :admin_root
  end

  constraints Clearance::Constraints::SignedOut.new do
    root to: 'sessions#new'
  end


  get '/react_test' => 'users#react_test'


  post '/firebase_update/:id' => 'airconds#update_website_from_firebase', as: :firebase_update
  resources :aircond_groups, only: [:create,:destroy,:index,:show]

  resources :devices
  resources :airconds do
    resources :versions, only: [:index]
  end
  get 'aircond/:id/timer' => 'airconds#timer', as: :set_timer
  patch 'aircond/:id/timer' => 'airconds#timer_set', as: :timer_set
  post 'set_all_status/:status' => 'airconds#set_all_status', as: :set_all_status
  post 'limit_options' => 'airconds#limit_options', as: :limit_options
  patch 'aircond/:id/assign_group' => 'airconds#assign_group', as: :assign_group

  post '/app_state/:id' => 'airconds#app_set', as: :app_set

  get '/auth/nextacademy/callback' => 'sessions#create_from_omniauth'

  resources :phone_apps, only: [:index]
  post '/app_create' => 'phone_apps#create', as: :app_create
  patch '/approve_token/:id' => 'phone_apps#approve_token', as: :approve_token
  get '/get_token' => 'phone_apps#provide_token', as: :get_token
  get '/validate_token' => 'phone_apps#check_token', as: :validate_token
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

aircond_rails_app/app/models/user.rb
class User < ApplicationRecord
  include Clearance::User
 	  enum role:{
	    'admin' =>0,
	    'common' =>1
	  }
  has_many :authentications, :dependent => :destroy

  @@oauth = false

  def self.create_with_auth_and_hash(authentication, auth_hash)
      if auth_hash["info"]["admin"]==true
        user = User.create!(email: auth_hash["info"]["email"])
        user.authentications << (authentication)      
        return user
      else
        return nil
      end
  end

  def self.oauth_sign_up?(bool)
    @@oauth = bool
  end

  def password_optional?
      true if @@oauth == true
  end
end

aircond_rails_app/app/controllers/users_controller.rb
class UsersController < Clearance::UsersController
	def dashboard
		@current_time = Time.zone.now
		@airconds = Aircond.all.order(:id)
    @aircond_groups = AircondGroup.not_empty
	end

  def react_test
  end

end

aircond_rails_app/app/views/users/_currenttime.html.erb
      <div id=current_time style='font-size: 50px'><span id=current_hour><%= "#{@current_time.hour}".rjust(2,'0')%></span>:<span id=current_min><%="#{@current_time.min}".rjust(2,'0')%></span>:<span id=current_sec><%="#{@current_time.sec}".rjust(2,'0')%></span></div>

      <div>Timezone: <%=Time.zone%></div>

aircond_rails_app/app/views/users/_form.html.erb
<div class="text-field">
  <%= form.label :email %>
  <%= form.text_field :email, type: 'email' %>
</div>

<div class="password-field">
  <%= form.label :password %>
  <%= form.password_field :password %>
</div>

aircond_rails_app/app/views/users/backup_for_dashboard.html.erb
    <% ac = Aircond.first%>
    <div class='col-sm-4' >
 <div class='ac_row' style= 'background-color: #E8E8EE;height:auto;width:auto;min-height: 100px; margin-bottom: 5px'>
        <div class = 'ac_status_test' style = 'clear:both;float:right;height:100px;width:40%'>
          <% status = ac.image_new(:status)%>

              <%= image_tag(status[:img_url],class:'fit-img-size ' , align:'middle')%>


        </div>
        <div style = 'float:left;height:50px;font-size:30px;width:60%;text-align: center;vertical-align: middle;font-style:italic;'><%= ac.alias%> 
        </div>
        <div style = 'float:left;clear:left;height:50px;width:20%'>
        <!-- <span style = 'font-size:15px;float:left;font-style:italic; '>Mode</span> -->
        <% mode = ac.image_new(:mode)%> 
            <%= image_tag(mode[:img_url],class:'fit-img-size ', align:'middle' )%>
        </div>
        <div style = 'float:left;height:50px;width:20%;text-align: center;font-size:30px'>
        <% fan_speed = ac.image_new(:fan_speed)%> 
          <% if fan_speed[:value] == 'NA'%>
            <%= fan_speed[:value]%> 
          <% else %>
            <%= image_tag(fan_speed[:img_url],class:'fit-img-size ', align:'middle' )%>
          <%end%>
        </div>
        <div style = 'float:left;height:50px;width:20%;text-align: center;font-size:30px'>
        <% temperature = ac.image_new(:temperature)%>
            <%= image_tag(temperature[:img_url],class:'fit-img-size ', align:'middle' )%>
        </div>
      </div>
      <!-- Next -->
      <div class='ac_row' style= 'background-color:   #fdf6e3;height:auto;width:auto;min-height: 100px; margin-bottom: 5px'>
        <div class = 'ac_status_test' style = 'clear:both;float:right;height:100px;width:40%'>
          <% status = ac.image_new(:status)%>

              <%= image_tag(status[:img_url],class:'fit-img-size ' , align:'middle')%>


        </div>
        <div style = 'float:left;height:50px;font-size:30px;width:60%;text-align: center;vertical-align: middle;font-style:italic;'><%= ac.alias%> 
        </div>
        <div style = 'float:left;clear:left;height:50px;width:20%'>
<!--         <span style = 'font-size:15px;float:left;font-style:italic; '>Mode</span> -->
        <% mode = ac.image_new(:mode)%> 
            <%= image_tag(mode[:img_url],class:'fit-img-size ', align:'middle' )%>
        </div>
        <div style = 'float:left;height:50px;width:20%;text-align: center;font-size:30px'>
        <% fan_speed = ac.image_new(:fan_speed)%> 
          <% if fan_speed[:value] == 'NA'%>
            <%= fan_speed[:value]%> 
          <% else %>
            <%= image_tag(fan_speed[:img_url],class:'fit-img-size ', align:'middle' )%>
          <%end%>
        </div>
        <div style = 'float:left;height:50px;width:20%;text-align: center;font-size:30px'>
        <% temperature = ac.image_new(:temperature)%>
            <%= image_tag(temperature[:img_url],class:'fit-img-size ', align:'middle' )%>
        </div>
      </div>
    </div>

<!--     <div class='col-sm-1' >Column Split</div> -->
    <div class='col-sm-4' >
      <div class='ac_row' style= 'background-color: #E8E8EE;height:auto;width:auto;min-height: 100px; margin-bottom: 5px'>
        <div class = 'ac_status_test' style = 'clear:both;float:right;height:100px;width:40%'>
          <% status = ac.image_new(:status)%>

              <%= image_tag(status[:img_url],class:'fit-img-size ' , align:'middle')%>


        </div>
        <div style = 'float:left;height:50px;font-size:30px;width:60%;text-align: center;vertical-align: middle;font-style:italic;'><%= ac.alias%> 
        </div>
        <div style = 'float:left;clear:left;height:50px;width:20%'>
        <!-- <span style = 'font-size:15px;float:left;font-style:italic; '>Mode</span> -->
        <% mode = ac.image_new(:mode)%> 
            <%= image_tag(mode[:img_url],class:'fit-img-size ', align:'middle' )%>
        </div>
        <div style = 'float:left;height:50px;width:20%;text-align: center;font-size:30px'>
        <% fan_speed = ac.image_new(:fan_speed)%> 
          <% if fan_speed[:value] == 'NA'%>
            <%= fan_speed[:value]%> 
          <% else %>
            <%= image_tag(fan_speed[:img_url],class:'fit-img-size ', align:'middle' )%>
          <%end%>
        </div>
        <div style = 'float:left;height:50px;width:20%;text-align: center;font-size:30px'>
        <% temperature = ac.image_new(:temperature)%>
            <%= image_tag(temperature[:img_url],class:'fit-img-size ', align:'middle' )%>
        </div>
      </div>
      <!-- Next -->
      <div class='ac_row' style= 'background-color:   #fdf6e3;height:auto;width:auto;min-height: 100px; margin-bottom: 5px'>
        <div class = 'ac_status_test' style = 'clear:both;float:right;height:100px;width:40%'>
          <% status = ac.image_new(:status)%>

              <%= image_tag(status[:img_url],class:'fit-img-size ' , align:'middle')%>


        </div>
        <div style = 'float:left;height:50px;font-size:30px;width:60%;text-align: center;vertical-align: middle;font-style:italic;'><%= ac.alias%> 
        </div>
        <div style = 'float:left;clear:left;height:50px;width:20%'>
<!--         <span style = 'font-size:15px;float:left;font-style:italic; '>Mode</span> -->
        <% mode = ac.image_new(:mode)%> 
            <%= image_tag(mode[:img_url],class:'fit-img-size ', align:'middle' )%>
        </div>
        <div style = 'float:left;height:50px;width:20%;text-align: center;font-size:30px'>
        <% fan_speed = ac.image_new(:fan_speed)%> 
          <% if fan_speed[:value] == 'NA'%>
            <%= fan_speed[:value]%> 
          <% else %>
            <%= image_tag(fan_speed[:img_url],class:'fit-img-size ', align:'middle' )%>
          <%end%>
        </div>
        <div style = 'float:left;height:50px;width:20%;text-align: center;font-size:30px'>
        <% temperature = ac.image_new(:temperature)%>
            <%= image_tag(temperature[:img_url],class:'fit-img-size ', align:'middle' )%>
        </div>
      </div>
    </div>
    
        <div class='col-sm-4' >
      <div class='ac_row' style= 'background-color: #E8E8EE;height:auto;width:auto;min-height: 100px; margin-bottom: 5px'>
        <div class = 'ac_status_test' style = 'clear:both;float:right;height:100px;width:40%'>
          <% status = ac.image_new(:status)%>

              <%= image_tag(status[:img_url],class:'fit-img-size ' , align:'middle')%>


        </div>
        <div style = 'float:left;height:50px;font-size:30px;width:60%;text-align: center;vertical-align: middle;font-style:italic;'><%= ac.alias%> 
        </div>
        <div style = 'float:left;clear:left;height:50px;width:20%'>
        <!-- <span style = 'font-size:15px;float:left;font-style:italic; '>Mode</span> -->
        <% mode = ac.image_new(:mode)%> 
            <%= image_tag(mode[:img_url],class:'fit-img-size ', align:'middle' )%>
        </div>
        <div style = 'float:left;height:50px;width:20%;text-align: center;font-size:30px'>
        <% fan_speed = ac.image_new(:fan_speed)%> 
          <% if fan_speed[:value] == 'NA'%>
            <%= fan_speed[:value]%> 
          <% else %>
            <%= image_tag(fan_speed[:img_url],class:'fit-img-size ', align:'middle' )%>
          <%end%>
        </div>
        <div style = 'float:left;height:50px;width:20%;text-align: center;font-size:30px'>
        <% temperature = ac.image_new(:temperature)%>
            <%= image_tag(temperature[:img_url],class:'fit-img-size ', align:'middle' )%>
        </div>
      </div>
      <!-- Next -->
      <div class='ac_row' style= 'background-color:   #fdf6e3;height:auto;width:auto;min-height: 100px; margin-bottom: 5px'>
        <div class = 'ac_status_test' style = 'clear:both;float:right;height:100px;width:40%'>
          <% status = ac.image_new(:status)%>

              <%= image_tag(status[:img_url],class:'fit-img-size ' , align:'middle')%>


        </div>
        <div style = 'float:left;height:50px;font-size:30px;width:60%;text-align: center;vertical-align: middle;font-style:italic;'><%= ac.alias%> 
        </div>
        <div style = 'float:left;clear:left;height:50px;width:20%'>
<!--         <span style = 'font-size:15px;float:left;font-style:italic; '>Mode</span> -->
        <% mode = ac.image_new(:mode)%> 
            <%= image_tag(mode[:img_url],class:'fit-img-size ', align:'middle' )%>
        </div>
        <div style = 'float:left;height:50px;width:20%;text-align: center;font-size:30px'>
        <% fan_speed = ac.image_new(:fan_speed)%> 
          <% if fan_speed[:value] == 'NA'%>
            <%= fan_speed[:value]%> 
          <% else %>
            <%= image_tag(fan_speed[:img_url],class:'fit-img-size ', align:'middle' )%>
          <%end%>
        </div>
        <div style = 'float:left;height:50px;width:20%;text-align: center;font-size:30px'>
        <% temperature = ac.image_new(:temperature)%>
            <%= image_tag(temperature[:img_url],class:'fit-img-size ', align:'middle' )%>
        </div>
      </div>
    </div>
    

      <div class='col-sm-4' >
      <div id = <%= "#{ac.id}"%> class = 'aircond ac_row'  style= 'background-color: #E8E8EE;height:auto;width:auto;min-height: 100px; margin-bottom: 5px'>
        <div class = 'ac_status_test ac_status' id = <%="#{ac.alias}"%> style = 'clear:both;float:right;height:100px;width:40%'>
          <% status = ac.image_new(:status)%>
              <%= image_tag(status[:img_url],class:'fit-img-size ' , align:'middle')%>
        </div>
        <div style = 'float:left;height:50px;font-size:30px;width:60%;text-align: center;vertical-align: middle;font-style:italic;'><%= ac.alias%> 
        </div>
        <div class = "ac_mode" style = 'float:left;clear:left;height:50px;width:20%'>
        <!-- <span style = 'font-size:15px;float:left;font-style:italic; '>Mode</span> -->
        <% mode = ac.image_new(:mode)%> 
            <%= image_tag(mode[:img_url],class:'fit-img-size ', align:'middle' )%>
        </div>
        <div  class = "ac_fan_speed" style = 'float:left;height:50px;width:20%;text-align: center;font-size:30px'>
        <% fan_speed = ac.image_new(:fan_speed)%> 
          <% if fan_speed[:value] == 'NA'%>
            <%= fan_speed[:value]%> 
          <% else %>
            <%= image_tag(fan_speed[:img_url],class:'fit-img-size ', align:'middle' )%>
          <%end%>
        </div>
        <div class = "ac_temperature" style = 'float:left;height:50px;width:20%;text-align: center;font-size:30px'>
        <% temperature = ac.image_new(:temperature)%>
          <% if temperature[:value] == 'NA'%>
            <%= temperature[:value]%> 
          <% else %>
            <%= image_tag(temperature[:img_url],class:'fit-img-size ', align:'middle' )%>
          <% end %>
        </div>
      </div>
    </div>

aircond_rails_app/app/views/users/dashboard.html.erb
    <div class="col-sm-10" id='user_dashboard' >
			<h1>Air Conditioners</h1>
				<%= flash[:warning]%>
				<%= flash[:notice]%>
        <div class= 'col-sm-12 head'>
            <span style = 'float:right'><%= link_to 'Mobile Apps', phone_apps_path, method:'get',class:"btn btn-primary get-btn" %></span>
        </div>

        <div class= 'col-sm-12 body'>
            <%= render partial:'/aircond_groups/aircond_index',locals:{aircond_groups:@aircond_groups}%>
        </div>

        <div class= 'col-sm-12 foot'>
            <span style= 'float:left'><%= link_to "Add Aircond", new_aircond_path, method:'get',class:"btn btn-primary get-btn" %></span>
            <span style= 'float:left'><%= link_to "Assign Group", aircond_groups_path, method:'get',class:"btn btn-primary get-btn" %></span>

            <span style= 'float:right'>
                <%= form_for :aircond, url:set_all_status_path('ON') do |f|%>
                    <%= f.hidden_field :group_title, value:'ALL'%>
                    <%= f.submit'ON', style: "width:110px",class:"btn btn-primary submit-btn"  %>
                <% end %>
            </span>
            <span style= 'float:right'>
                <%= form_for :aircond, url:set_all_status_path('OFF') do |f|%>
                    <%= f.hidden_field :group_title, value:'ALL'%>
                    <%= f.submit'OFF', style: "width:110px",class:"btn btn-primary submit-btn"  %>
                <% end %>                    
            </span>
            <span style = 'float:right'><%= select_tag 'group_title', options_for_select(["ALL"] + AircondGroup.all.pluck(:title) ),class:"form-control", id:'group_selector'  %></span>
        </div>

    </div>


    <div class="col-sm-2" style = 'border-left-style: solid;border-bottom-style: solid; padding: 20px;text-align : right'>
      <%= render partial:'/users/currenttime'%>
    </div>

aircond_rails_app/app/views/users/new.html.erb
<div id="clearance" class="sign-up">
  <h2><%= t(".title") %></h2>

  <%= form_for @user do |form| %>
    <%= render partial: '/users/form', object: form %>

    <div class="submit-field">
      <%= form.submit %>
    </div>

  <% end %>
</div>

aircond_rails_app/app/views/users/react_test.html.erb
<%

air1 = { title: 'Far-Left',  ontime: '8:00', offtime: '21:00', power: true, mode: "cool", temp: 26, fan: 0 }
air2 = { title: 'Middle-Left', ontime: '8:15', offtime: '21:30', power: false, mode: "dry", temp: 23, fan: 0 }
air3 = { title: 'Middle-Right', ontime: '9:00', offtime: '21:40', power: false, mode: "cool", temp: 21, fan: 0 }
air4 = { title: 'Far-Right', ontime: '10:00', offtime: '20:50', power: true, mode: "cool", temp: 19, fan: 0 }

%>

<div class="flex-container">
  <div style="padding: 0px 12px;"><%= react_component("CardContainer", air1) %></div>
  <div style="padding: 0px 12px;"><%= react_component("CardContainer", air2) %></div>
  <div style="padding: 0px 12px;"><%= react_component("CardContainer", air3) %></div>
  <div style="padding: 0px 12px;"><%= react_component("CardContainer", air4) %></div>
</div>