aircond_rails_app/config/routes.rb
require 'sidekiq/web'
require 'sidekiq/cron/web'
Rails.application.routes.draw do

mount Sidekiq::Web => '/sidekiq'
  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "sessions", only: [:create]

  resources :users, controller: "users", only: [:create] do
    resource :password,
      controller: "clearance/passwords",
      only: [:create, :edit, :update]
  end

  get "/sign_in" => "sessions#new", as: "sign_in"
  delete "/sign_out" => "sessions#destroy", as: "sign_out"
  constraints Clearance::Constraints::SignedIn.new do
    root to: 'aircond_groups#index', as: :admin_root
  end

  constraints Clearance::Constraints::SignedOut.new do
    root to: 'sessions#new'
  end


  get '/react_test' => 'users#react_test'


  post '/firebase_update/:id' => 'airconds#update_website_from_firebase', as: :firebase_update
  resources :aircond_groups, only: [:create,:destroy,:index,:show]

  resources :devices
  resources :airconds do
    resources :versions, only: [:index]
  end
  get 'aircond/:id/timer' => 'airconds#timer', as: :set_timer
  patch 'aircond/:id/timer' => 'airconds#timer_set', as: :timer_set
  post 'set_all_status/:status' => 'airconds#set_all_status', as: :set_all_status
  post 'limit_options' => 'airconds#limit_options', as: :limit_options
  patch 'aircond/:id/assign_group' => 'airconds#assign_group', as: :assign_group

  post '/app_state/:id' => 'airconds#app_set', as: :app_set

  get '/auth/nextacademy/callback' => 'sessions#create_from_omniauth'

  resources :phone_apps, only: [:index]
  post '/app_create' => 'phone_apps#create', as: :app_create
  patch '/approve_token/:id' => 'phone_apps#approve_token', as: :approve_token
  get '/get_token' => 'phone_apps#provide_token', as: :get_token
  get '/validate_token' => 'phone_apps#check_token', as: :validate_token
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

aircond_rails_app/app/views/layouts/_navbar.html.erb
<nav class="navbar next-navbar">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href=<%=root_path%>><img class= resize src="https://nextacademy.com/img/nav-logo.png"></a>
    </div>
     <ul class="nav navbar-nav navbar-left"> 
     <li>
       <a href=<%=root_path%>>Aircons</a>
     </li>
     </ul>  
    <ul class="nav navbar-nav navbar-right">
	    <%if signed_in?%>
	    	<li><a href=<%=sign_out_path%> data-method= delete ><span class="glyphicon glyphicon-log-out"></span> Sign Out</a></li>
	    <%else%>
	      <li><a href=<%=sign_in_path%>><span class="glyphicon glyphicon-log-in"></span> Sign In</a></li>
    	<%end%>
    </ul>
  </div>
</nav>

aircond_rails_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ProjectHoustonServer</title>
    <%= csrf_meta_tags %>
    <script src="https://www.gstatic.com/firebasejs/3.6.5/firebase.js"></script>
    <script>
      var config = {
        databaseURL: "https://nextaircon-6d849.firebaseio.com",
      };
      firebase.initializeApp(config);
    </script>

    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400" rel="stylesheet">
    
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>	
      
  </head>

  <body >
  	<%# render '/layouts/navbar'%>
    <%= yield %>
  </body>
</html>